# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import Dict, List, Union, Optional
from typing_extensions import Literal, Annotated, TypeAlias

from pydantic import Field as FieldInfo

from ..._utils import PropertyInfo
from ..._models import BaseModel

__all__ = [
    "PolicyEnforceResponse",
    "Evaluation",
    "EvaluationPromptInjectionEvaluation",
    "EvaluationPromptInjectionEvaluationThread",
    "EvaluationContentSafetyEvaluation",
    "EvaluationContentSafetyEvaluationThread",
    "EvaluationDataLeakageEvaluation",
    "EvaluationDataLeakageEvaluationThread",
    "EvaluationContextSafetyEvaluation",
    "EvaluationContextSafetyEvaluationThread",
]


class EvaluationPromptInjectionEvaluationThread(BaseModel):
    """Thread details for prompt injection guardrail."""

    content_identifier: int = FieldInfo(alias="contentIdentifier")
    """Index of the chunk/part within the message."""

    message_identifier: int = FieldInfo(alias="messageIdentifier")
    """Index of the message containing the issue."""

    score: float
    """Confidence score for this detection."""


class EvaluationPromptInjectionEvaluation(BaseModel):
    """Evaluation payload for prompt injection guardrail."""

    action: Literal["block", "redact", "detect", "allow"]
    """Action suggested by this guardrail (allow, detect, redact, block)."""

    guardrail_key: Literal["prompt-injection-protection"] = FieldInfo(alias="guardrailKey")
    """Guardrail key that produced this evaluation."""

    score: float
    """Overall confidence score."""

    metadata: Optional[Dict[str, object]] = None
    """Additional guardrail-specific metadata."""

    threads: Optional[List[EvaluationPromptInjectionEvaluationThread]] = None
    """Evidence or reasoning threads generated by the guardrail."""


class EvaluationContentSafetyEvaluationThread(BaseModel):
    """Thread details for content safety guardrail."""

    category: Literal["hate", "crime", "sexual", "violence"]
    """Content safety category hit by the message."""

    content_identifier: int = FieldInfo(alias="contentIdentifier")
    """Index of the chunk/part within the message."""

    message_identifier: int = FieldInfo(alias="messageIdentifier")
    """Index of the message containing the issue."""

    score: float
    """Confidence score for the category."""


class EvaluationContentSafetyEvaluation(BaseModel):
    """Evaluation payload for content safety guardrail."""

    action: Literal["block", "redact", "detect", "allow"]
    """Action suggested by this guardrail (allow, detect, redact, block)."""

    guardrail_key: Literal["content-moderation"] = FieldInfo(alias="guardrailKey")
    """Guardrail key that produced this evaluation."""

    score: float
    """Overall confidence score."""

    metadata: Optional[Dict[str, object]] = None
    """Additional guardrail-specific metadata."""

    threads: Optional[List[EvaluationContentSafetyEvaluationThread]] = None
    """Evidence or reasoning threads generated by the guardrail."""


class EvaluationDataLeakageEvaluationThread(BaseModel):
    """Thread details for data leakage guardrail."""

    category: Literal[
        "name",
        "email",
        "phone",
        "address",
        "location",
        "date",
        "ssn",
        "credit_card",
        "bank_account",
        "id_number",
        "ip_address",
        "url",
        "username",
        "password",
        "api_key",
        "organization",
        "other",
    ]
    """Detected PII/secret category (email, phone, etc)."""

    content_identifier: int = FieldInfo(alias="contentIdentifier")
    """Index of the chunk/part within the message."""

    message_identifier: int = FieldInfo(alias="messageIdentifier")
    """Index of the message containing the leak."""

    score: float
    """Confidence score for the detection."""

    span: str
    """Detected span of text that triggered the guardrail."""


class EvaluationDataLeakageEvaluation(BaseModel):
    """Evaluation payload for data leakage guardrail."""

    action: Literal["block", "redact", "detect", "allow"]
    """Action suggested by this guardrail (allow, detect, redact, block)."""

    guardrail_key: Literal["data-leakage-prevention"] = FieldInfo(alias="guardrailKey")
    """Guardrail key that produced this evaluation."""

    score: float
    """Overall confidence score."""

    metadata: Optional[Dict[str, object]] = None
    """Additional guardrail-specific metadata."""

    threads: Optional[List[EvaluationDataLeakageEvaluationThread]] = None
    """Evidence or reasoning threads generated by the guardrail."""


class EvaluationContextSafetyEvaluationThread(BaseModel):
    """Thread details for context safety guardrail."""

    content_identifier: int = FieldInfo(alias="contentIdentifier")
    """Index of the chunk/part within the message."""

    message_identifier: int = FieldInfo(alias="messageIdentifier")
    """Index of the message containing the issue."""

    score: float
    """Confidence score for the topic."""

    topic: str
    """Topic label that was flagged."""


class EvaluationContextSafetyEvaluation(BaseModel):
    """Evaluation payload for context safety guardrail."""

    action: Literal["block", "redact", "detect", "allow"]
    """Action suggested by this guardrail (allow, detect, redact, block)."""

    guardrail_key: Literal["topic-control"] = FieldInfo(alias="guardrailKey")
    """Guardrail key that produced this evaluation."""

    score: float
    """Overall confidence score."""

    metadata: Optional[Dict[str, object]] = None
    """Additional guardrail-specific metadata."""

    threads: Optional[List[EvaluationContextSafetyEvaluationThread]] = None
    """Evidence or reasoning threads generated by the guardrail."""


Evaluation: TypeAlias = Annotated[
    Union[
        EvaluationPromptInjectionEvaluation,
        EvaluationContentSafetyEvaluation,
        EvaluationDataLeakageEvaluation,
        EvaluationContextSafetyEvaluation,
    ],
    PropertyInfo(discriminator="guardrail_key"),
]


class PolicyEnforceResponse(BaseModel):
    """Policy enforcement response schema."""

    action: Literal["block", "redact", "detect", "allow"]
    """Overall action decided by the policy (allow, detect, redact, block)."""

    enforcer_identifier: str = FieldInfo(alias="enforcerIdentifier")
    """Identifier of the policy enforcer that processed the request."""

    evaluations: Optional[List[Evaluation]] = None
    """Per-guardrail evaluation results."""
